============================= test session starts ==============================
platform darwin -- Python 3.8.2, pytest-7.3.1, pluggy-1.0.0 -- /Users/coleopter/src/bdd-coder/.tox/pytest/bin/python
cachedir: .tox/pytest/.pytest_cache
rootdir: /Users/coleopter/src/bdd-coder
configfile: pytest.ini
plugins: asyncio-0.21.0, cov-4.0.0
asyncio: mode=strict
collecting ... collected 5 items

example/advanced_tests/test_stories.py::TestClearBoard::test_odd_boards[even-9] FAILED [ 20%]
example/advanced_tests/test_stories.py::TestClearBoard::test_start_board[Goat-8-Boring-9] PASSED [ 40%]
example/advanced_tests/test_stories.py::TestClearBoard::test_start_board[Cat-6-Funny-11] PASSED [ 60%]
example/advanced_tests/test_stories.py::TestClearBoard::test_start_colored_board[0-Red-8-Boring-9] PASSED [ 80%]
example/advanced_tests/test_stories.py::TestClearBoard::test_start_colored_board[1-Green-6-Funny-11] PASSED [100%]
example/advanced_tests/test_stories.py::TestClearBoard::test_start_colored_board[1-Green-6-Funny-11] ERROR [100%]

==================================== ERRORS ====================================
_ ERROR at teardown of TestClearBoard.test_start_colored_board[1-Green-6-Funny-11] _

    def teardown_module():
>       base.BddTester.gherkin.log(fail_if_pending=True)
E       Failed: These scenarios did not run: pending_scenario

example/advanced_tests/test_stories.py:5: Failed
------------------------------ Captured log setup ------------------------------
__________________________
├─2022-10-16 21:32:59.058845 ✔ NewGame.i_request_a_new_game_with_n_boards
|    n = 6 
|  ↦ 'game'
├─2022-10-16 21:32:59.059026 ✔ NewGame.a_game_of_kind_is_created_with_boards_of_guess_count_guesses
|    kind = 'Funny'
|    guess_count = 11 
└─2022-10-16 21:32:59.059080 ✅ NewGame.even_boards
├─2022-10-16 21:32:59.059166 ✔ TestClearBoard.i_request_a_clear_board_in_my_new_game 
|  ↦ 'request-result'
|    'board-result'
├─2022-10-16 21:32:59.059349 ✔ TestClearBoard.the_nth_board_is_added_with_the_color
|    nth = 1
|    n = 6
|    color = 'Green'
|    pytestconfig = <_pytest.config.Config object at 0x103c354c0> 
└─2022-10-16 21:32:59.059404 ✅ TestClearBoard.test_start_colored_board
---------------------------- Captured log teardown -----------------------------
3✅  1❌  1❓
=================================== FAILURES ===================================
____________________ TestClearBoard.test_odd_boards[even-9] ____________________
Traceback (most recent call last):
  File "/Users/coleopter/src/bdd-coder/example/advanced_tests/test_stories.py", line 43, in i_get_a_400_response_saying_it_must_be
    assert False, 'Forced error'
AssertionError: Forced error
assert False
---------------------------- Captured stdout setup -----------------------------
Specification files generated in .tmp-specs
Test case hierarchy validated
------------------------------ Captured log setup ------------------------------
__________________________
├─2022-10-16 21:32:58.994179 ✔ NewGame.i_request_a_new_game_with_n_boards
|    n = 9 
|  ↦ 'game'
├─2022-10-16 21:32:58.994483 ✖ NewGame.i_get_a_400_response_saying_it_must_be
|    even ↦ Traceback (most recent call last):
|  File [36m"/Users/coleopter/src/bdd-coder/example/advanced_tests/test_stories.py"[39;49;00m, line [34m43[39;49;00m, in i_get_a_400_response_saying_it_must_be
|    [34massert[39;49;00m [34mFalse[39;49;00m, [33m'[39;49;00m[33mForced error[39;49;00m[33m'[39;49;00m
|[91mAssertionError[39;49;00m: Forced error
|assert False
└─2022-10-16 21:32:59.051911 ❌ NewGame.test_odd_boards
=========================== short test summary info ============================
FAILED example/advanced_tests/test_stories.py::TestClearBoard::test_odd_boards[even-9]
ERROR example/advanced_tests/test_stories.py::TestClearBoard::test_start_colored_board[1-Green-6-Funny-11]
===================== 1 failed, 4 passed, 1 error in 0.18s =====================
